
Enum "role_enum" {
  "admin"
  "user"
  "moderator"
}

Enum "status_enum" {
  "In Progress"
  "Completed"
  "Dormant"
}

Table "categories" {
  "id" uuid [not null, default: `public.uuid_generate_v4()`]
  "user_id" uuid
  "name" "character varying(255)" [not null]
  "description" "character varying(255)"
  "created_at" timestamp [default: `now()`]
  "updated_at" timestamp [default: `now()`]
}

Table "contributions" {
  "id" uuid [not null, default: `public.uuid_generate_v4()`]
  "saving_id" uuid [not null]
  "amount" numeric(30,3) [not null]
  "date" timestamp
  "created_at" timestamp [default: `now()`]
}

Table "expenses" {
  "id" uuid [not null, default: `public.uuid_generate_v4()`]
  "user_id" uuid
  "category_id" uuid
  "description" "character varying(255)"
  "amount" numeric(30,3) [not null]
  "date" timestamp
  "created_at" timestamp [default: `now()`]
  "updated_at" timestamp [default: `now()`]

Indexes {
  category_id [type: btree, name: "expenses_category_idx"]
  user_id [type: btree, name: "expenses_user_id_idx"]
}
}

Table "savings" {
  "id" uuid [not null, default: `public.uuid_generate_v4()`]
  "user_id" uuid
  "description" "character varying(255)" [not null]
  "category_id" uuid
  "target_amount" numeric(30,3) [not null]
  "priority" "character varying(255)"
  "status" status_enum [default: `'In Progress'::public.status_enum`]
  "target_date" timestamp
  "start_date" timestamp [default: `now()`]
  "created_at" timestamp [default: `now()`]
  "updated_at" timestamp [default: `now()`]

Indexes {
  category_id [type: btree, name: "savings_category_idx"]
  priority [type: btree, name: "savings_priority_idx"]
  status [type: btree, name: "savings_status_idx"]
  user_id [type: btree, name: "savings_user_id_idx"]
}
}

Table "security_answers" {
  "id" uuid [not null, default: `public.uuid_generate_v4()`]
  "question_id" uuid [not null]
  "user_id" uuid [not null]
  "answer" "character varying(255)" [not null]
  "created_at" timestamp [default: `now()`]
  "updated_at" timestamp [default: `now()`]
}

Table "security_questions" {
  "id" uuid [not null, default: `public.uuid_generate_v4()`]
  "user_id" uuid
  "question" "character varying(255)" [not null]
  "created_at" timestamp [default: `now()`]
}

Table "users" {
  "id" uuid [not null, default: `public.uuid_generate_v4()`]
  "first_name" "character varying(255)" [not null]
  "last_name" "character varying(255)" [not null]
  "phone_number" "character varying(255)"
  "role" role_enum [not null, default: `'user'::public.role_enum`]
  "password" "character varying(255)" [not null]
  "created_at" timestamp [default: `now()`]
  "updated_at" timestamp [default: `now()`]
}

Ref "categories_user_id_fkey":"users"."id" < "categories"."user_id"

Ref "contributions_saving_id_fkey":"savings"."id" < "contributions"."saving_id" [delete: cascade]

Ref "expenses_category_id_fkey":"categories"."id" < "expenses"."category_id"

Ref "expenses_user_id_fkey":"users"."id" < "expenses"."user_id" [delete: cascade]

Ref "savings_category_id_fkey":"categories"."id" < "savings"."category_id"

Ref "savings_user_id_fkey":"users"."id" < "savings"."user_id" [delete: cascade]

Ref "security_answers_question_id_fkey":"security_questions"."id" < "security_answers"."question_id"

Ref "security_answers_user_id_fkey":"users"."id" < "security_answers"."user_id"

Ref "security_questions_user_id_fkey":"users"."id" < "security_questions"."user_id"
