info:
  version: 1.0.0
  title: SAPI
  description: API for managing invitations
tags:
  - name: Savings
    description: Endpoints for managing invitations
openapi: ""
components:
  schemas: {}
  parameters: {}
paths:
  "/invitations/{groupId}":
    post:
      summary: Invite a user to a certain group
      tags:
        - Invitations
      parameters:
        - schema:
            type: string
          required: true
          name: phone_number
          in: path
      responses:
        "200":
          description: Invite sent successfully
        "400":
          description: User already has a pending invitation for this group
        "404":
          description: User already has a pending invitation for this group
        "500":
          description: Internal server error.
  "/savings/records/{id}":
    patch:
      summary: Get a saving by ID
      tags:
        - Savings
      parameters:
        - schema:
            type: string
          required: true
          name: id
          in: path
      responses:
        "200":
          description: Saving retrieved successfully
        "403":
          description: Unprocessable entity
        "500":
          description: Internal server error.
  /invitations/my-invites:
    get:
      summary: Get recived group invites
      tags:
        - Invitations
      responses:
        "200":
          description: Saving created successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    receiver_id:
                      type: number
                    sender_id:
                      type: number
                    group_id:
                      type: number
                    created_at:
                      type: string
                  required:
                    - receiver_id
                    - sender_id
                    - group_id
                    - created_at
        "403":
          description: Unprocessable entity
        "500":
          description: Internal server error.
