import { activitySchema } from "./getActivity";

const responseData = [
    {
      type: 'WithdrawalRequest',
      id: 29,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 80,
      metadata: { reason: 'test', recipients: [Array] },
      created_at: '2025-02-26T11:20:22.600Z'
    },
    {
      type: 'Deposit',
      id: 18,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 100000,
      metadata: null,
      created_at: '2025-02-26T11:19:44.406Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 28,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 8090,
      metadata: { reason: 'bbbbbbb', recipients: [Array] },
      created_at: '2025-02-26T07:23:04.594Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 27,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 80,
      metadata: { reason: 'fun', recipients: [Array] },
      created_at: '2025-02-18T11:38:11.364Z'
    },
    {
      type: 'MemberJoined',
      id: 11,
      actor_id: 173,
      actor_name: 'James Kariuki',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-18T11:14:42.381Z'
    },
    {
      type: 'MemberJoined',
      id: 2,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-18T11:14:42.381Z'
    },
    {
      type: 'MemberJoined',
      id: 3,
      actor_id: 38,
      actor_name: 'Grace Wanjiku',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-18T11:14:42.381Z'
    },
    {
      type: 'MemberJoined',
      id: 4,
      actor_id: 110,
      actor_name: 'Michael Mwangi',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-18T11:14:42.381Z'
    },
    {
      type: 'MemberJoined',
      id: 5,
      actor_id: 114,
      actor_name: 'Isaac Gathoni',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at:'2025-02-18T11:14:42.381Z'
    },
    {
      type: 'MemberJoined',
      id: 6,
      actor_id: 115,
      actor_name: 'Michael Mwangi',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-18T11:14:42.381Z'
    },
    {
      type: 'MemberJoined',
      id: 7,
      actor_id: 116,
      actor_name: 'Samuel Otieno',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-18T11:14:42.381Z'
    },
    {
      type: 'MemberJoined',
      id: 8,
      actor_id: 117,
      actor_name: 'Alaine',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-18T11:14:42.381Z'
    },
    {
      type: 'MemberJoined',
      id: 9,
      actor_id: 118,
      actor_name: 'Johnson M',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-18T11:14:42.381Z'
    },
    {
      type: 'MemberJoined',
      id: 10,
      actor_id: 119,
      actor_name: 'Cung',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-18T11:14:42.381Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 23,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '2444', status: 'Approved' },
      created_at: '2025-02-17T11:11:45.739Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 22,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 56,
      metadata: { reason: '56', status: 'Approved' },
      created_at: '2025-02-17T09:25:12.357Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 26,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 200,
      metadata: { reason: '2000', recipients: [Array] },
      created_at: '2025-02-17T09:12:59.201Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 25,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 15,
      metadata: { reason: '4555', recipients: [Array] },
      created_at: '2025-02-17T09:12:38.717Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 24,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 124,
      metadata: { reason: '234', recipients: [Array] },
      created_at: '2025-02-17T09:11:58.502Z'
    },
    {
      type: 'Transfer',
      id: 14,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: 80,
      metadata: { source_pocket: [Object], destination_pocket: [Object] },
      created_at: '2025-02-17T08:45:20.902Z'
    },
    {
      type: 'Deposit',
      id: 13,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 100000,
      metadata: null,
      created_at: '2025-02-17T07:54:31.881Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 23,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '2444', recipients: [Array] },
      created_at: '2025-02-14T12:00:21.113Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 18,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 16,
      metadata: { reason: 'rrr', status: 'Rejected' },
      created_at: '2025-02-14T12:00:05.487Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 22,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 56,
      metadata: { reason: '56', recipients: [Array] },
      created_at: '2025-02-14T11:54:44.767Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 17,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 16,
      metadata: { reason: '12', status: 'Approved' },
      created_at: '2025-02-14T11:53:03.143Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 15,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '444', status: 'Rejected' },
      created_at: '2025-02-14T11:51:44.219Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 14,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '444', status: 'Approved' },
      created_at: '2025-02-14T11:51:30.636Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 16,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 15,
      metadata: { reason: '555', status: 'Approved' },
      created_at:'2025-02-14T11:50:00.924Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 13,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '444', status: 'Rejected' },
      created_at: '2025-02-14T11:49:04.946Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 12,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '444', status: 'Rejected' },
      created_at: '2025-02-14T11:47:42.337Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 19,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 17,
      metadata: { reason: 'REason 17', status: 'Rejected' },
      created_at: '2025-02-14T11:46:44.354Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 20,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 18,
      metadata: { reason: 'reason 18', status: 'Approved' },
      created_at: '2025-02-14T11:45:21.099Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 11,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 13,
      metadata: { reason: '3333', status: 'Rejected' },
      created_at: '2025-02-14T11:43:10.830Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 9,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 256,
      metadata: { reason: 'tttt', status: 'Rejected' },
      created_at: '2025-02-14T11:42:13.048Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 21,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 19,
      metadata: { reason: '1999', status: 'Approved' },
      created_at: '2025-02-14T09:32:08.006Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 21,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 19,
      metadata: { reason: '1999', recipients: [Array] },
      created_at: '2025-02-14T09:30:14.944Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 20,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 18,
      metadata: { reason: 'reason 18', recipients: [Array] },
      created_at: '2025-02-14T09:28:35.690Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 19,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 17,
      metadata: { reason: 'REason 17', recipients: [Array] },
      created_at: '2025-02-14T09:26:38.361Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 7,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 80,
      metadata: { reason: 'testtt', status: 'Approved' },
      created_at: +'2025-02-14T09:24:17.132Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 10,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 12,
      metadata: { reason: 'testing', status: 'Approved' },
      created_at: '2025-02-14T09:21:31.762Z'
    },
    {
      type: 'Deposit',
      id: 5,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 2,
      pocket_name: 'Pocket 1 For trial',
      amount: 256,
      metadata: null,
      created_at: '2025-02-14T09:08:20.974Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 18,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 16,
      metadata: { reason: 'rrr', recipients: [Array] },
      created_at: '2025-02-14T08:53:34.096Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 17,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 16,
      metadata: { reason: '12', recipients: [Array] },
      created_at: '2025-02-14T08:52:57.851Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 16,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 15,
      metadata: { reason: '555', recipients: [Array] },
      created_at: '2025-02-14T08:50:13.498Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 15,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '444', recipients: [Array] },
      created_at: '2025-02-14T08:48:08.762Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 14,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '444', recipients: [Array] },
      created_at: '2025-02-14T08:45:27.177Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 13,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '444', recipients: [Array] },
      created_at: '2025-02-14T08:44:57.085Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 12,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 14,
      metadata: { reason: '444', recipients: [Array] },
      created_at: '2025-02-14T08:44:03.528Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 11,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 13,
      metadata: { reason: '3333', recipients: [Array] },
      created_at: '2025-02-14T08:42:33.617Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 10,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 12,
      metadata: { reason: 'testing', recipients: [Array] },
      created_at: '2025-02-14T08:39:28.991Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 9,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 256,
      metadata: { reason: 'tttt', recipients: [Array] },
      created_at: '2025-02-14T08:19:33.799Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 5,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 20,
      metadata: { reason: 'just because', status: 'Approved' },
      created_at: '2025-02-14T08:18:29.699Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 8,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 206,
      metadata: { reason: 'ddddd', status: 'Rejected' },
      created_at: '2025-02-14T08:18:02.323Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 4,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 12,
      metadata: { reason: 'tttt', status: 'Rejected' },
      created_at: '2025-02-14T08:17:47.030Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 6,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 256,
      metadata: { reason: 'ttt', status: 'Rejected' },
      created_at: '2025-02-14T08:17:11.774Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 8,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 206,
      metadata: { reason: 'ddddd', recipients: [Array] },
      created_at: '2025-02-14T08:16:36.030Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 7,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 80,
      metadata: { reason: 'testtt', recipients: [Array] },
      created_at: '2025-02-14T08:15:09.134Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 6,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 256,
      metadata: { reason: 'ttt', recipients: [Array] },
      created_at: '2025-02-13T12:42:09.816Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 3,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 20,
      metadata: { reason: 'just because', status: 'Approved' },
      created_at: '2025-02-13T10:37:09.981Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 5,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 20,
      metadata: { reason: 'just because', recipients: [Array] },
      created_at: '2025-02-13T09:20:25.352Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 4,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 12,
      metadata: { reason: 'tttt', recipients: [Array] },
      created_at: '2025-02-13T07:36:07.146Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 3,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 20,
      metadata: { reason: 'just because', recipients: [Array] },
      created_at: '2025-02-13T07:28:16.205Z'
    },
    {
      type: 'Deposit',
      id: 2,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 200,
      metadata: null,
      created_at: '2025-02-13T07:27:04.539Z'
    },
    {
      type: 'WithdrawalRejection',
      id: 2,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 20,
      metadata: { reason: 'Spending', status: 'Rejected' },
      created_at: '2025-02-13T07:10:58.503Z'
    },
    {
      type: 'WithdrawalApproval',
      id: 1,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 20,
      metadata: { reason: 'Spending', status: 'Approved' },
      created_at: '2025-02-10T13:20:25.099Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 2,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 20,
      metadata: { reason: 'Spending', recipients: [Array] },
      created_at: '2025-02-06T09:40:25.795Z'
    },
    {
      type: 'WithdrawalRequest',
      id: 1,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 20,
      metadata: { reason: 'Spending', recipients: [Array] },
      created_at: '2025-02-06T09:38:53.340Z'
    },
    {
      type: 'Deposit',
      id: 1,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: 1,
      pocket_name: 'Group Wallet',
      amount: 200,
      metadata: null,
      created_at: '2025-02-06T09:32:49.292Z'
    },
    {
      type: 'MemberJoined',
      id: 1,
      actor_id: 15,
      actor_name: 'Munderu2',
      target_id: null,
      target_name: null,
      pocket_id: null,
      pocket_name: null,
      amount: null,
      metadata: null,
      created_at: '2025-02-06T09:24:42.104Z'
    }
  ]
  
  const parsedData = responseData.map((item) => activitySchema.parse(item));
  console.log(parsedData);