info:
  version: 1.0.0
  title: SAPI
  description: API for managing admins
tags:
  - name: Admin
    description: Admin Only endpoints
openapi: ""
components:
  schemas: {}
  parameters: {}
paths:
  /admin:
    post:
      summary: Create a new admin
      tags:
        - Admin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                gender:
                  type: string
                  enum:
                    &a1
                    - Male
                    - Female
                    - Prefer not to say
                national_id:
                  type: integer
                  minimum: 10000000
                  maximum: 99999999
                phone_number:
                  type: string
                pin:
                  type: string
              required:
                - full_name
                - gender
                - national_id
                - phone_number
                - pin
      responses:
        "200":
          description: Account created Succesfully.Procced to login
        "500":
          description: Internal server error.
  "/admin/financial-stats/{resource}/{operator}":
    get:
      summary: " Get table statistics"
      tags:
        - Admin
      parameters:
        - schema:
            type: string
          required: true
          name: resource
          in: path
        - schema:
            type: string
          required: true
          name: operator
          in: path
        - schema:
            type: string
          required: false
          name: user_id
          in: query
        - schema:
            type: string
          required: false
          name: priority
          in: query
        - schema:
            type: string
          required: false
          name: status
          in: query
        - schema:
            type: string
          required: false
          name: category_id
          in: query
        - schema:
            type: string
          required: false
          name: start_date
          in: query
        - schema:
            type: string
          required: false
          name: end_date
          in: query
      responses:
        "200":
          description: Stat computed succesfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totals:
                    type: number
                required:
                  - totals
        "403":
          description: Unprocessable entity
        "500":
          description: Internal server error.
  "/admin/{roleToUpdate}/{id}":
    patch:
      summary: Either upgrade or downgrade user role
      tags:
        - Admin
      parameters:
        - schema:
            type: string
          required: true
          name: roleToUpdate
          in: path
        - schema:
            type: string
          required: true
          name: id
          in: path
      responses:
        "200":
          description: User role succesfully updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  full_name:
                    type: string
                  gender:
                    type: string
                    enum: *a1
                  id:
                    type: number
                  role:
                    type: string
                    enum:
                      - Admin
                required:
                  - full_name
                  - gender
                  - id
                  - role
        "403":
          description: Unprocessable entity
        "500":
          description: Internal server error.
