info:
  version: 1.0.0
  title: Security Questions API
  description: API for managing security questions
tags:
  - name: Security Answers
    description: Endpoints for managing security answers
openapi: ""
components:
  schemas: {}
  parameters: {}
paths:
  /security-answers:
    post:
      summary: Create a security answer
      tags:
        - Security Answers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                question_id:
                  type: number
                answer:
                  type: string
              required:
                - question_id
                - answer
      responses:
        "200":
          description: Security answer created successfully.
        "403":
          description: " Unprocessable entity"
        "500":
          description: Internal server error.
    patch:
      summary: Create a security answer
      tags:
        - Security Answers
      parameters:
        - schema:
            type: string
          required: true
          name: id
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question_id:
                  type: number
                answer:
                  type: string
              required:
                - question_id
                - answer
      responses:
        "200":
          description: Answer updated successfully
        "403":
          description: " Unprocessable entity"
        "500":
          description: Internal server error.
