tags:
  - name: Group Admin
    description: Group Admin management API endpoints

/group-admin/{group_id}:
  post:
    summary: Make a user a group administrator
    tags: [Group Admin]
    parameters:
      - in: path
        name: group_id
        schema:
          type: string
        required: true
        description: The ID of the group to make a user an administrator for.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              user_id:
                type: integer
                description: The ID of the user to make an administrator.
    responses:
      200:
        description: User made a group administrator successfully.
      400:
        description: Error occurred during group administrator creation.
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: Error message indicating the reason for failure.

/group-admin/nominate/{group_id}:
  post:
    summary: Nominate a group administrator for a specific group
    tags: [Group Admin]
    parameters:
      - in: path
        name: group_id
        schema:
          type: string
        required: true
        description: The ID of the group to nominate an administrator for.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              user_id:
                type: integer
                description: The ID of the user to nominate as an administrator.
    responses:
      200:
        description: Member nominated as admin.
      400:
        description: Error occurred during group administrator nomination.
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: Error message indicating the reason for failure.

/group-admin/nominate/{group_id}/{nominated_member_id}:
  post:
    summary: Approve the nomination of a member as a group administrator
    tags: [Group Admin]
    parameters:
      - in: path
        name: group_id
        schema:
          type: string
        required: true
        description: The ID of the group.
      - in: path
        name: nominated_member_id
        schema:
          type: string
        required: true
        description: The ID of the member nominated as an administrator.
    responses:
      200:
        description: Nomination recorded successfully.
      500:
        description: Internal server error.


  get:
    summary: Get nominated administrators for a group
    tags: [Group Admin]
    parameters:
      - in: path
        name: group_id
        schema:
          type: string
        required: true
        description: The ID of the group to get nominated administrators for.
    responses:
      200:
        description: List of nominated administrators for the group.
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  group_id:
                    type: integer
                  user_id:
                    type: integer
                  full_name:
                    type: string
                  nominated_at:
                    type: string
                    format: date-time
      500:
        description: Internal server error.
