info:
  version: 1.0.0
  title: SAPI
  description: API for managing Culmulatives
tags:
  - name: Cumulatives
    description: Endpoints for managing cumulatives
openapi: ""
components:
  schemas: {}
  parameters: {}
paths:
  /cumulatives/top-expenditure-categories:
    get:
      summary: Returns an array of categories with the most expenditure in order with
        their total expenses
      tags:
        - Cumulatives
      responses:
        "200":
          description: ": Categories with highest expenses retrieved successfully."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    category_id:
                      type: number
                    total_expense:
                      type: number
                  required:
                    - category_id
                    - total_expense
        "500":
          description: Internal server error.
  "/cumulatives/total-expenses:":
    get:
      summary: Gets total expenses
      tags:
        - Cumulatives
      parameters:
        - schema:
            type: string
          required: false
          name: startDate
          in: path
        - schema:
            type: string
          required: false
          name: endDate
          in: path
        - schema:
            type: string
          required: false
          name: categoryId
          in: path
      responses:
        "200":
          description: Total expenses retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_expenses:
                    type: number
                required:
                  - total_expenses
        "500":
          description: Internal server error.
  /cumulatives/total-savings:
    patch:
      summary: Get individual total savings
      tags:
        - Cumulatives
      responses:
        "200":
          description: Saving retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_savings:
                    type: number
                required:
                  - total_savings
        "500":
          description: Internal server error.
  /cumulatives/total-target-amount:
    patch:
      summary: Get a saving by ID
      tags:
        - Cumulatives
      parameters:
        - schema:
            type: string
          required: false
          name: priority
          in: path
        - schema:
            type: string
          required: false
          name: status
          in: path
        - schema:
            type: string
          required: false
          name: category_id
          in: path
      responses:
        "200":
          description: Total target amount retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_target_amount:
                    type: number
                required:
                  - total_target_amount
        "403":
          description: Unprocessable entity
        "500":
          description: Internal server error.
