tags:
  - name: Savings
    description: Savings management API endpoints

components:
  schemas:
    Saving:
      type: object
      required:
        - id
        - user_id
        - goal_id
        - amount
      properties:
        id:
          type: integer
          description: The unique identifier of the savings record.
        user_id:
          type: integer
          description: The ID of the user associated with the savings record.
        goal_id:
          type: integer
          description: The ID of the goal associated with the savings record.
        amount:
          type: number
          description: The amount saved.
      example:
        id: 1
        user_id: 1
        goal_id: 1
        amount: 100.00

paths:
  /savings:
    post:
      summary: Create a new saving
      tags: [Savings]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - amount
              properties:
                goal_id:
                  type: integer
                amount:
                  type: number
      responses:
        200:
          description: Saving created successfully.
        400:
          description: Error occurred during saving creation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating the reason for failure.

  /savings/records/{id}:
    get:
      summary: Get a saving by ID
      tags: [Savings]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: The ID of the saving to retrieve.
      responses:
        200:
          description: Saving retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Saving'
        404:
          description: Saving not found.

  /savings/{savingIdentifier}:
    get:
      summary: Get savings by conditions
      tags: [Savings]
      parameters:
        - in: path
          name: savingIdentifier
          schema:
            type: string
          required: true
          description: |
            Defines the scope of users to retrieve. Can be one of the following:
            - "me": Retrieves information about the currently logged-in users savings.
            - "all": Retrieves information about all users savings(requires Admin or Moderator role).
            - A user ID: Retrieves information about a specific users savings based on their ID.
              Standard users can only request their own user ID. Admins and moderators can request any user ID.
      responses:
        200:
          description: Savings retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Saving'
        404:
          description: Savings not found.


