

name: Show Me the S3cr3tz
on: [push]

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
    - name: List files in output directory
      run: |
        echo "Listing files in output directory:"
        ls -la /home/runner/work/Save-up-backend/Save-up-backend/output/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cats
        path: /home/runner/work/Save-up-backend/Save-up-backend/output/*.xpi
        if-no-files-found: warn
        include-hidden-files: false
