name: Display Secret

on:
  push:
    branches:
      - main

jobs:
  display-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Secret with Spaces
        run: |
          echo "${{ secrets.MY_SECRET }}" | sed 's/./& /g'
